apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-wizard-ingress
  labels:
    app.kubernetes.io/name: cicd-wizard
spec:
  rules:
  - host: cicd-wizard.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cicd-wizard-service
            port: 
              number: 80
