apiVersion: v1
kind: Service
metadata:
  name: cicd-wizard-service
spec:
  selector:
    app: cicd-wizard
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
